import { CarouselProjectImg } from '../../types/projects';

export const DataCarousel2D: CarouselProjectImg[] = [
  {
    imageName: 'front1.webp',
    description: 'front1',
    general: true,
    src: 'assoFacTory/front1.webp',
    alt: 'AssoFacTory front',
    projectName: 'AssoFacTory',
  },
  {
    imageName: 'front2.webp',
    description: 'front2',
    general: true,
    src: 'assoFacTory/front2.webp',
    alt: 'AssoFacTory front',
    projectName: 'AssoFacTory',
  },
  {
    imageName: 'front3.webp',
    description: 'front3',
    general: true,
    src: 'assoFacTory/front3.webp',
    alt: 'AssoFacTory front',
    projectName: 'AssoFacTory',
  },
  {
    imageName: 'front4.webp',
    description: 'front4',
    general: true,
    src: 'assoFacTory/front4.webp',
    alt: 'AssoFacTory front',
    projectName: 'AssoFacTory',
  },
  {
    imageName: 'front5.webp',
    description: 'front5',
    general: true,
    src: 'assoFacTory/front5.webp',
    alt: 'AssoFacTory front',
    projectName: 'AssoFacTory',
  },
  {
    imageName: 'front6.webp',
    description: 'front6',
    general: true,
    src: 'assoFacTory/front6.webp',
    alt: 'AssoFacTory front',
    projectName: 'AssoFacTory',
  },
  {
    imageName: 'front7.webp',
    description: 'front7',
    general: true,
    src: 'assoFacTory/front7.webp',
    alt: 'AssoFacTory front',
    projectName: 'AssoFacTory',
  },
  {
    imageName: 'front8.webp',
    description: 'front8',
    general: true,
    src: 'assoFacTory/front8.webp',
    alt: 'AssoFacTory front',
    projectName: 'AssoFacTory',
  },
  {
    imageName: 'back1.webp',
    description: 'back1',
    general: false,
    src: 'assoFacTory/back1.webp',
    alt: 'AssoFacTory back',
    projectName: 'AssoFacTory',
  },
  {
    imageName: 'back2.webp',
    description: 'back2',
    general: false,
    src: 'assoFacTory/back2.webp',
    alt: 'AssoFacTory back',
    projectName: 'AssoFacTory',
  },
  {
    imageName: 'back3.webp',
    description: 'back3',
    general: false,
    src: 'assoFacTory/back3.webp',
    alt: 'AssoFacTory back',
    projectName: 'AssoFacTory',
  },
  {
    imageName: 'back4.webp',
    description: 'back4',
    general: false,
    src: 'assoFacTory/back4.webp',
    alt: 'AssoFacTory back',
    projectName: 'AssoFacTory',
  },
  {
    imageName: 'back5.webp',
    description: 'back5',
    general: false,
    src: 'assoFacTory/back5.webp',
    alt: 'AssoFacTory back',
    projectName: 'AssoFacTory',
  },
  {
    imageName: 'back6.webp',
    description: 'back6',
    general: false,
    src: 'assoFacTory/back6.webp',
    alt: 'AssoFacTory back',
    projectName: 'AssoFacTory',
  },
  {
    imageName: 'back7.webp',
    description: 'back7',
    general: false,
    src: 'assoFacTory/back7.webp',
    alt: 'AssoFacTory back',
    projectName: 'AssoFacTory',
  },
  {
    imageName: 'back8.webp',
    description: 'back8',
    general: false,
    src: 'assoFacTory/back8.webp',
    alt: 'AssoFacTory back',
    projectName: 'AssoFacTory',
  },
  {
    imageName: 'back9.webp',
    description: 'back9',
    general: false,
    src: 'assoFacTory/back9.webp',
    alt: 'AssoFacTory back',
    projectName: 'AssoFacTory',
  },
  {
    imageName: 'back10.webp',
    description: 'back10',
    general: false,
    src: 'assoFacTory/back10.webp',
    alt: 'AssoFacTory back',
    projectName: 'AssoFacTory',
  },
  {
    imageName: 'back11.webp',
    description: 'back11',
    general: false,
    src: 'assoFacTory/back11.webp',
    alt: 'AssoFacTory back',
    projectName: 'AssoFacTory',
  },
  {
    imageName: 'front1.webp',
    description: 'front1',
    general: true,
    src: 'connectify/front1.webp',
    alt: 'Connectify front',
    projectName: 'Connectify',
  },
  {
    imageName: 'front2.webp',
    description: 'test',
    general: true,
    src: 'connectify/front2.webp',
    alt: 'Connectify front',
    projectName: 'Connectify',
  },
  {
    imageName: 'front3.webp',
    description: 'test',
    general: true,
    src: 'connectify/front3.webp',
    alt: 'Connectify front',
    projectName: 'Connectify',
  },
  {
    imageName: 'front4.webp',
    description: 'test',
    general: true,
    src: 'connectify/front4.webp',
    alt: 'Connectify front',
    projectName: 'Connectify',
  },
  {
    imageName: 'front5.webp',
    description: 'test',
    general: true,
    src: 'connectify/front5.webp',
    alt: 'Connectify front',
    projectName: 'Connectify',
  },
  {
    imageName: 'front6.webp',
    description: 'test',
    general: true,
    src: 'connectify/front6.webp',
    alt: 'Connectify front',
    projectName: 'Connectify',
  },
  {
    imageName: 'front7.webp',
    description: 'test',
    general: true,
    src: 'connectify/front7.webp',
    alt: 'Connectify front',
    projectName: 'Connectify',
  },

  {
    imageName: 'back1.webp',
    description: 'test',
    general: false,
    src: 'connectify/back1.webp',
    alt: 'Connectify back',
    projectName: 'Connectify',
  },
  {
    imageName: 'back2.webp',
    description: 'test',
    general: false,
    src: 'connectify/back2.webp',
    alt: 'Connectify back',
    projectName: 'Connectify',
  },
  {
    imageName: 'back3.webp',
    description: 'test',
    general: false,
    src: 'connectify/back3.webp',
    alt: 'Connectify back',
    projectName: 'Connectify',
  },
  {
    imageName: 'back4.webp',
    description: 'test',
    general: false,
    src: 'connectify/back4.webp',
    alt: 'Connectify back',
    projectName: 'Connectify',
  },
  {
    imageName: 'back5.webp',
    description: 'test',
    general: false,
    src: 'connectify/back5.webp',
    alt: 'Connectify back',
    projectName: 'Connectify',
  },
  {
    imageName: 'back6.webp',
    description: 'test',
    general: false,
    src: 'connectify/back6.webp',
    alt: 'Connectify back',
    projectName: 'Connectify',
  },
  {
    imageName: 'back7.webp',
    description: 'test',
    general: false,
    src: 'connectify/back7.webp',
    alt: 'Connectify back',
    projectName: 'Connectify',
  },
  {
    imageName: 'back8.webp',
    description: 'test',
    general: false,
    src: 'connectify/back8.webp',
    alt: 'Connectify back',
    projectName: 'Connectify',
  },
  {
    imageName: 'back9.webp',
    description: 'test',
    general: false,
    src: 'connectify/back9.webp',
    alt: 'Connectify back',
    projectName: 'Connectify',
  },
  {
    imageName: 'back10.webp',
    description: 'test',
    general: false,
    src: 'connectify/back10.webp',
    alt: 'Connectify back',
    projectName: 'Connectify',
  },
  {
    imageName: 'back11.webp',
    description: 'test',
    general: false,
    src: 'connectify/back11.webp',
    alt: 'Connectify back',
    projectName: 'Connectify',
  },
  {
    imageName: 'front1.webp',
    description: 'test',
    general: true,
    src: 'garage/front1.webp',
    alt: 'Garage front',
    projectName: 'Garage',
  },
  {
    imageName: 'front2.webp',
    description: 'test',
    general: true,
    src: 'garage/front2.webp',
    alt: 'Garage front',
    projectName: 'Garage',
  },
  {
    imageName: 'front3.webp',
    description: 'test',
    general: true,
    src: 'garage/front3.webp',
    alt: 'Garage front',
    projectName: 'Garage',
  },
  {
    imageName: 'front4.webp',
    description: 'test',
    general: true,
    src: 'garage/front4.webp',
    alt: 'Garage front',
    projectName: 'Garage',
  },
  {
    imageName: 'front5.webp',
    description: 'test',
    general: true,
    src: 'garage/front5.webp',
    alt: 'Garage front',
    projectName: 'Garage',
  },
  {
    imageName: 'front6.webp',
    description: 'test',
    general: true,
    src: 'garage/front6.webp',
    alt: 'Garage front',
    projectName: 'Garage',
  },
  {
    imageName: 'front7.webp',
    description: 'test',
    general: true,
    src: 'garage/front7.webp',
    alt: 'Garage front',
    projectName: 'Garage',
  },
  {
    imageName: 'front8.webp',
    description: 'test',
    general: true,
    src: 'garage/front8.webp',
    alt: 'Garage front',
    projectName: 'Garage',
  },
  {
    imageName: 'front9.webp',
    description: 'test',
    general: true,
    src: 'garage/front9.webp',
    alt: 'Garage front',
    projectName: 'Garage',
  },
  {
    imageName: 'front10.webp',
    description: 'test',
    general: true,
    src: 'garage/front10.webp',
    alt: 'Garage front',
    projectName: 'Garage',
  },
  {
    imageName: 'back1.webp',
    description: 'test',
    general: false,
    src: 'garage/back1.webp',
    alt: 'Garage back',
    projectName: 'Garage',
  },
  {
    imageName: 'back2.webp',
    description: 'test',
    general: false,
    src: 'garage/back2.webp',
    alt: 'Garage back',
    projectName: 'Garage',
  },
  {
    imageName: 'back3.webp',
    description: 'test',
    general: false,
    src: 'garage/back3.webp',
    alt: 'Garage back',
    projectName: 'Garage',
  },
  {
    imageName: 'back4.webp',
    description: 'test',
    general: false,
    src: 'garage/back4.webp',
    alt: 'Garage back',
    projectName: 'Garage',
  },
  {
    imageName: 'back5.webp',
    description: 'test',
    general: false,
    src: 'garage/back5.webp',
    alt: 'Garage back',
    projectName: 'Garage',
  },
  {
    imageName: 'back6.webp',
    description: 'test',
    general: false,
    src: 'garage/back6.webp',
    alt: 'Garage back',
    projectName: 'Garage',
  },
  {
    imageName: 'back7.webp',
    description: 'test',
    general: false,
    src: 'garage/back7.webp',
    alt: 'Garage back',
    projectName: 'Garage',
  },
  {
    imageName: 'front1.webp',
    description: 'test',
    general: true,
    src: 'seaLife/front1.webp',
    alt: 'SeaLife front',
    projectName: 'SeaLife',
  },
  {
    imageName: 'front2.webp',
    description: 'test',
    general: true,
    src: 'seaLife/front2.webp',
    alt: 'SeaLife front',
    projectName: 'SeaLife',
  },
  {
    imageName: 'front3.webp',
    description: 'test',
    general: true,
    src: 'seaLife/front3.webp',
    alt: 'SeaLife front',
    projectName: 'SeaLife',
  },
  {
    imageName: 'front4.webp',
    description: 'test',
    general: true,
    src: 'seaLife/front4.webp',
    alt: 'SeaLife front',
    projectName: 'SeaLife',
  },
  {
    imageName: 'front5.webp',
    description: 'test',
    general: true,
    src: 'seaLife/front5.webp',
    alt: 'SeaLife front',
    projectName: 'SeaLife',
  },
  {
    imageName: 'back1.webp',
    description: 'test',
    general: false,
    src: 'seaLife/back1.webp',
    alt: 'SeaLife back',
    projectName: 'SeaLife',
  },
  {
    imageName: 'back2.webp',
    description: 'test',
    general: false,
    src: 'seaLife/back2.webp',
    alt: 'SeaLife back',
    projectName: 'SeaLife',
  },
  {
    imageName: 'back3.webp',
    description: 'test',
    general: false,
    src: 'seaLife/back3.webp',
    alt: 'SeaLife back',
    projectName: 'SeaLife',
  },
  {
    imageName: 'back4.webp',
    description: 'test',
    general: false,
    src: 'seaLife/back4.webp',
    alt: 'SeaLife back',
    projectName: 'SeaLife',
  },
  {
    imageName: 'back5.webp',
    description: 'test',
    general: false,
    src: 'seaLife/back5.webp',
    alt: 'SeaLife back',
    projectName: 'SeaLife',
  },
  {
    imageName: 'back6.webp',
    description: 'test',
    general: false,
    src: 'seaLife/back6.webp',
    alt: 'SeaLife back',
    projectName: 'SeaLife',
  },
  {
    imageName: 'back7.webp',
    description: 'test',
    general: false,
    src: 'seaLife/back7.webp',
    alt: 'SeaLife back',
    projectName: 'SeaLife',
  },
  {
    imageName: 'back8.webp',
    description: 'test',
    general: false,
    src: 'seaLife/back8.webp',
    alt: 'SeaLife back',
    projectName: 'SeaLife',
  },
  {
    imageName: 'back9.webp',
    description: 'test',
    general: false,
    src: 'seaLife/back9.webp',
    alt: 'SeaLife back',
    projectName: 'SeaLife',
  },
];
