import { CarouselProjectImg } from "../../types/projects";

export const DataCarousel2D: CarouselProjectImg[] = [
  {
    imageName: "front1.png",
    description: "test",
    general: true,
    src: "assoFacTory/front1.png",
    alt: "AssoFacTory front",
    projectName: "AssoFacTory",
  },
  {
    imageName: "front2.png",
    description: "test",
    general: true,
    src: "assoFacTory/front2.png",
    alt: "AssoFacTory front",
    projectName: "AssoFacTory",
  },
  {
    imageName: "front3.png",
    description: "test",
    general: true,
    src: "assoFacTory/front3.png",
    alt: "AssoFacTory front",
    projectName: "AssoFacTory",
  },
  {
    imageName: "front4.png",
    description: "test",
    general: true,
    src: "assoFacTory/front4.png",
    alt: "AssoFacTory front",
    projectName: "AssoFacTory",
  },
  {
    imageName: "front5.png",
    description: "test",
    general: true,
    src: "assoFacTory/front5.png",
    alt: "AssoFacTory front",
    projectName: "AssoFacTory",
  },
  {
    imageName: "front6.png",
    description: "test",
    general: true,
    src: "assoFacTory/front6.png",
    alt: "AssoFacTory front",
    projectName: "AssoFacTory",
  },
  {
    imageName: "front7.png",
    description: "test",
    general: true,
    src: "assoFacTory/front7.png",
    alt: "AssoFacTory front",
    projectName: "AssoFacTory",
  },
  {
    imageName: "front8.png",
    description: "test",
    general: true,
    src: "assoFacTory/front8.png",
    alt: "AssoFacTory front",
    projectName: "AssoFacTory",
  },
  {
    imageName: "back1.png",
    description: "test",
    general: false,
    src: "assoFacTory/back1.png",
    alt: "AssoFacTory back",
    projectName: "AssoFacTory",
  },
  {
    imageName: "back2.png",
    description: "test",
    general: false,
    src: "assoFacTory/back2.png",
    alt: "AssoFacTory back",
    projectName: "AssoFacTory",
  },
  {
    imageName: "back3.png",
    description: "test",
    general: false,
    src: "assoFacTory/back3.png",
    alt: "AssoFacTory back",
    projectName: "AssoFacTory",
  },
  {
    imageName: "back4.png",
    description: "test",
    general: false,
    src: "assoFacTory/back4.png",
    alt: "AssoFacTory back",
    projectName: "AssoFacTory",
  },
  {
    imageName: "back5.png",
    description: "test",
    general: false,
    src: "assoFacTory/back5.png",
    alt: "AssoFacTory back",
    projectName: "AssoFacTory",
  },
  {
    imageName: "back6.png",
    description: "test",
    general: false,
    src: "assoFacTory/back6.png",
    alt: "AssoFacTory back",
    projectName: "AssoFacTory",
  },
  {
    imageName: "back7.png",
    description: "test",
    general: false,
    src: "assoFacTory/back7.png",
    alt: "AssoFacTory back",
    projectName: "AssoFacTory",
  },
  {
    imageName: "back8.png",
    description: "test",
    general: false,
    src: "assoFacTory/back8.png",
    alt: "AssoFacTory back",
    projectName: "AssoFacTory",
  },
  {
    imageName: "back9.png",
    description: "test",
    general: false,
    src: "assoFacTory/back9.png",
    alt: "AssoFacTory back",
    projectName: "AssoFacTory",
  },
  {
    imageName: "back10.png",
    description: "test",
    general: false,
    src: "assoFacTory/back10.png",
    alt: "AssoFacTory back",
    projectName: "AssoFacTory",
  },
  {
    imageName: "back11.png",
    description: "test",
    general: false,
    src: "assoFacTory/back11.png",
    alt: "AssoFacTory back",
    projectName: "AssoFacTory",
  },
  {
    imageName: "front1.png",
    description: "test",
    general: true,
    src: "connectify/front1.png",
    alt: "Connectify front",
    projectName: "Connectify",
  },
  {
    imageName: "front2.png",
    description: "test",
    general: true,
    src: "connectify/front2.png",
    alt: "Connectify front",
    projectName: "Connectify",
  },
  {
    imageName: "front3.png",
    description: "test",
    general: true,
    src: "connectify/front3.png",
    alt: "Connectify front",
    projectName: "Connectify",
  },
  {
    imageName: "front4.png",
    description: "test",
    general: true,
    src: "connectify/front4.png",
    alt: "Connectify front",
    projectName: "Connectify",
  },
  {
    imageName: "front5.png",
    description: "test",
    general: true,
    src: "connectify/front5.png",
    alt: "Connectify front",
    projectName: "Connectify",
  },
  {
    imageName: "front6.png",
    description: "test",
    general: true,
    src: "connectify/front6.png",
    alt: "Connectify front",
    projectName: "Connectify",
  },
  {
    imageName: "front7.png",
    description: "test",
    general: true,
    src: "connectify/front7.png",
    alt: "Connectify front",
    projectName: "Connectify",
  },

  {
    imageName: "back1.png",
    description: "test",
    general: false,
    src: "connectify/back1.png",
    alt: "Connectify back",
    projectName: "Connectify",
  },
  {
    imageName: "back2.png",
    description: "test",
    general: false,
    src: "connectify/back2.png",
    alt: "Connectify back",
    projectName: "Connectify",
  },
  {
    imageName: "back3.png",
    description: "test",
    general: false,
    src: "connectify/back3.png",
    alt: "Connectify back",
    projectName: "Connectify",
  },
  {
    imageName: "back4.png",
    description: "test",
    general: false,
    src: "connectify/back4.png",
    alt: "Connectify back",
    projectName: "Connectify",
  },
  {
    imageName: "back5.png",
    description: "test",
    general: false,
    src: "connectify/back5.png",
    alt: "Connectify back",
    projectName: "Connectify",
  },
  {
    imageName: "back6.png",
    description: "test",
    general: false,
    src: "connectify/back6.png",
    alt: "Connectify back",
    projectName: "Connectify",
  },
  {
    imageName: "back7.png",
    description: "test",
    general: false,
    src: "connectify/back7.png",
    alt: "Connectify back",
    projectName: "Connectify",
  },
  {
    imageName: "back8.png",
    description: "test",
    general: false,
    src: "connectify/back8.png",
    alt: "Connectify back",
    projectName: "Connectify",
  },
  {
    imageName: "back9.png",
    description: "test",
    general: false,
    src: "connectify/back9.png",
    alt: "Connectify back",
    projectName: "Connectify",
  },
  {
    imageName: "back10.png",
    description: "test",
    general: false,
    src: "connectify/back10.png",
    alt: "Connectify back",
    projectName: "Connectify",
  },
  {
    imageName: "back11.png",
    description: "test",
    general: false,
    src: "connectify/back11.png",
    alt: "Connectify back",
    projectName: "Connectify",
  },
  {
    imageName: "front1.png",
    description: "test",
    general: true,
    src: "garage/front1.png",
    alt: "Garage front",
    projectName: "Garage",
  },
  {
    imageName: "front2.png",
    description: "test",
    general: true,
    src: "garage/front2.png",
    alt: "Garage front",
    projectName: "Garage",
  },
  {
    imageName: "front3.png",
    description: "test",
    general: true,
    src: "garage/front3.png",
    alt: "Garage front",
    projectName: "Garage",
  },
  {
    imageName: "front4.png",
    description: "test",
    general: true,
    src: "garage/front4.png",
    alt: "Garage front",
    projectName: "Garage",
  },
  {
    imageName: "front5.png",
    description: "test",
    general: true,
    src: "garage/front5.png",
    alt: "Garage front",
    projectName: "Garage",
  },
  {
    imageName: "front6.png",
    description: "test",
    general: true,
    src: "garage/front6.png",
    alt: "Garage front",
    projectName: "Garage",
  },
  {
    imageName: "front7.png",
    description: "test",
    general: true,
    src: "garage/front7.png",
    alt: "Garage front",
    projectName: "Garage",
  },
  {
    imageName: "front8.png",
    description: "test",
    general: true,
    src: "garage/front8.png",
    alt: "Garage front",
    projectName: "Garage",
  },
  {
    imageName: "front9.png",
    description: "test",
    general: true,
    src: "garage/front9.png",
    alt: "Garage front",
    projectName: "Garage",
  },
  {
    imageName: "front10.png",
    description: "test",
    general: true,
    src: "garage/front10.png",
    alt: "Garage front",
    projectName: "Garage",
  },
  {
    imageName: "back1.png",
    description: "test",
    general: false,
    src: "garage/back1.png",
    alt: "Garage back",
    projectName: "Garage",
  },
  {
    imageName: "back2.png",
    description: "test",
    general: false,
    src: "garage/back2.png",
    alt: "Garage back",
    projectName: "Garage",
  },
  {
    imageName: "back3.png",
    description: "test",
    general: false,
    src: "garage/back3.png",
    alt: "Garage back",
    projectName: "Garage",
  },
  {
    imageName: "back4.png",
    description: "test",
    general: false,
    src: "garage/back4.png",
    alt: "Garage back",
    projectName: "Garage",
  },
  {
    imageName: "back5.png",
    description: "test",
    general: false,
    src: "garage/back5.png",
    alt: "Garage back",
    projectName: "Garage",
  },
  {
    imageName: "back6.png",
    description: "test",
    general: false,
    src: "garage/back6.png",
    alt: "Garage back",
    projectName: "Garage",
  },
  {
    imageName: "back7.png",
    description: "test",
    general: false,
    src: "garage/back7.png",
    alt: "Garage back",
    projectName: "Garage",
  },
  {
    imageName: "front1.png",
    description: "test",
    general: true,
    src: "seaLife/front1.png",
    alt: "SeaLife front",
    projectName: "SeaLife",
  },
  {
    imageName: "front2.png",
    description: "test",
    general: true,
    src: "seaLife/front2.png",
    alt: "SeaLife front",
    projectName: "SeaLife",
  },
  {
    imageName: "front3.png",
    description: "test",
    general: true,
    src: "seaLife/front3.png",
    alt: "SeaLife front",
    projectName: "SeaLife",
  },
  {
    imageName: "front4.png",
    description: "test",
    general: true,
    src: "seaLife/front4.png",
    alt: "SeaLife front",
    projectName: "SeaLife",
  },
  {
    imageName: "front5.png",
    description: "test",
    general: true,
    src: "seaLife/front5.png",
    alt: "SeaLife front",
    projectName: "SeaLife",
  },
  {
    imageName: "back1.png",
    description: "test",
    general: false,
    src: "seaLife/back1.png",
    alt: "SeaLife back",
    projectName: "SeaLife",
  },
  {
    imageName: "back2.png",
    description: "test",
    general: false,
    src: "seaLife/back2.png",
    alt: "SeaLife back",
    projectName: "SeaLife",
  },
  {
    imageName: "back3.png",
    description: "test",
    general: false,
    src: "seaLife/back3.png",
    alt: "SeaLife back",
    projectName: "SeaLife",
  },
  {
    imageName: "back4.png",
    description: "test",
    general: false,
    src: "seaLife/back4.png",
    alt: "SeaLife back",
    projectName: "SeaLife",
  },
  {
    imageName: "back5.png",
    description: "test",
    general: false,
    src: "seaLife/back5.png",
    alt: "SeaLife back",
    projectName: "SeaLife",
  },
  {
    imageName: "back6.png",
    description: "test",
    general: false,
    src: "seaLife/back6.png",
    alt: "SeaLife back",
    projectName: "SeaLife",
  },
  {
    imageName: "back7.png",
    description: "test",
    general: false,
    src: "seaLife/back7.png",
    alt: "SeaLife back",
    projectName: "SeaLife",
  },
  {
    imageName: "back8.png",
    description: "test",
    general: false,
    src: "seaLife/back8.png",
    alt: "SeaLife back",
    projectName: "SeaLife",
  },
  {
    imageName: "back9.png",
    description: "test",
    general: false,
    src: "seaLife/back9.png",
    alt: "SeaLife back",
    projectName: "SeaLife",
  },
];
