import { Carousel3d } from '../../types/projects';

export const imagesCarousel: Carousel3d[] = [
  {
    imageName: 'img1.png', //teamchallenge
    descriptions: 'React|Styled-components|Typecript|Mui-material|PostgreSQL|GitHub|Work in the team',
    linkGit: 'private',
    linkProject: 'https://teamchallenge.io/',
    linkVideo: 'https://youtu.be/b_6AnXj5OxM',
    src: '',
    degY: 0,
    alt: '',
    projectName: 'TeamChallenge',
    openProject: true,
    openGit: false,
    openVideo: true,
  },
  {
    imageName: 'img2.png', //diamondCollection
    descriptions: 'HTML|CSS|Javascript|Local storage for Basket|GitHub',
    linkGit: 'https://github.com/TinaSemashko/ProjetJavascriptAssofac',
    linkProject: 'https://loquacious-empanada-12b1c9.netlify.app/',
    linkVideo: '',
    src: '',
    degY: 0,
    alt: '',
    projectName: 'diamondCollection',
    openProject: true,
    openGit: true,
    openVideo: false,
  },
  {
    imageName: 'img3.png', //dictionary
    descriptions: 'HTML|CSS|React|Bootstrap|API|GitHub',
    linkGit: 'https://github.com/TinaSemashko/dictionary_react',
    linkProject: 'https://effortless-sunburst-a3a68f.netlify.app/',
    linkVideo: '',
    src: '',
    degY: 0,
    alt: '',
    projectName: 'dictionary',
    openProject: true,
    openGit: true,
    openVideo: false,
  },
  {
    imageName: 'img4.png', //ekea
    descriptions: 'HTML|CSS|Javascript|Bootstrap|JSON|Local storage for Basket|GitHub',
    linkGit: 'https://github.com/Kaiju971/PROJET-NIVEAU-II',
    linkProject: 'https://magical-cocada-6863e7.netlify.app/',
    linkVideo: '',
    src: '',
    degY: 0,
    alt: '',
    projectName: 'ekea',
    openProject: true,
    openGit: true,
    openVideo: false,
  },
  {
    imageName: 'img5.png', //casinoGame
    descriptions: 'HTML|CSS|Javascript|Bootstrap|GitHub',
    linkGit: 'https://github.com/TinaSemashko/AssofacCasinoGame',
    linkProject: 'https://aquamarine-gnome-52ee5d.netlify.app/',
    linkVideo: '',
    src: '',
    degY: 0,
    alt: '',
    projectName: 'casinoGame',
    openProject: true,
    openGit: true,
    openVideo: false,
  },
  {
    imageName: 'img6.png', //garage
    descriptions: 'React|Styled-components|Typecript|Mui-material|PostgreSQL|GitHub|CRUD',
    linkGit: 'https://github.com/TinaSemashko/garage',
    linkProject: 'https://www.tina-space.fr',
    linkVideo: 'Garage',
    src: '',
    degY: 0,
    alt: '',
    projectName: 'Garage',
    openProject: false,
    openGit: true,
    openVideo: false,
  },
  {
    imageName: 'img7.png', //Weather
    descriptions: 'HTML|CSS|Javascript|Bootstrap|API|GitHub',
    linkGit: 'https://github.com/TinaSemashko/Weather',
    linkProject: 'https://incandescent-cuchufli-36fc65.netlify.app/',
    linkVideo: '',
    src: '',
    degY: 0,
    alt: '',
    projectName: 'Weather',
    openProject: true,
    openGit: true,
    openVideo: false,
  },
  {
    imageName: 'img8.png', //weather_react
    descriptions: 'HTML|CSS|React|Bootstrap|API|GitHub',
    linkGit: 'https://github.com/TinaSemashko/weather_react',
    linkProject: 'https://stately-sopapillas-d6d214.netlify.app/',
    linkVideo: '',
    src: '',
    degY: 0,
    alt: '',
    projectName: 'weatherReact',
    openProject: true,
    openGit: true,
    openVideo: false,
  },
  {
    imageName: 'img9.png', //SeaLife
    descriptions: 'React|Styled-components|Typecript|Mui-material|PostgreSQL|GitHub|RestAPI|CRUD',
    linkGit: 'https://github.com/TinaSemashko/sealifeapi',
    linkProject: '',
    linkVideo: 'VideoSeaLife',
    src: '',
    degY: 0,
    alt: '',
    projectName: 'SeaLife',
    openProject: false,
    openGit: true,
    openVideo: true,
  },
  {
    imageName: 'img10.png', //connectify
    descriptions: 'React|Styled-components|Typecript|Mui-material|PostgreSQL|GitHub|CRUD',
    linkGit: 'https://github.com/TinaSemashko/connectify-plus',
    linkProject: '',
    linkVideo: 'VideoConnectify',
    src: '',
    degY: 0,
    alt: '',
    projectName: 'Connectify',
    openProject: false,
    openGit: true,
    openVideo: false,
  },
  {
    imageName: 'img11.png', //assoFacTory
    descriptions: 'React|Styled-components|Javascript|Mui-material|PostgreSQL|GitHub|Work in the team|CRUD',
    linkGit: 'https://github.com/TinaSemashko/AssoFacTorySQL',
    linkProject: '',
    linkVideo: 'VideoAssofactory',
    src: '',
    degY: 0,
    alt: '',
    projectName: 'AssoFacTory',
    openProject: false,
    openGit: true,
    openVideo: true,
  },
  {
    imageName: 'img12.png', //ABS
    descriptions: 'React|Styled-components|Typecript|Mui-material|PostgreSQL|GitHub|Work in the team|CRUD',
    linkGit: 'private',
    linkProject: 'https://www.abs-couverture.fr',
    linkVideo: 'VideoABS',
    src: '',
    degY: 0,
    alt: '',
    projectName: 'ABS',
    openProject: true,
    openGit: false,
    openVideo: true,
  },
];
