import { Carousel3d } from '../../types/projects';

export const imagesCarousel: Carousel3d[] = [
  {
    imageName: 'img1.webp', //teamchallenge
    descriptions: 'React|Styled-components|Typecript|Mui-material|PostgreSQL|GitHub|Work in the team',
    linkGit: 'private',
    linkProject: 'https://teamchallenge.io/',
    linkVideo: 'https://youtu.be/b_6AnXj5OxM',
    src: '',
    degY: 0,
    alt: 'Plateforme Web pour les juniors, qui rassemble une équipe interfonctionnelle pour son premier projet',
    projectName: 'TeamChallenge',
    openProject: true,
    openGit: false,
    openVideo: true,
  },
  {
    imageName: 'img2.webp', //diamondCollection
    descriptions: 'HTML|CSS|Javascript|Local storage for Basket|GitHub',
    linkGit: 'https://github.com/TinaSemashko/ProjetJavascriptAssofac',
    linkProject: 'https://loquacious-empanada-12b1c9.netlify.app/',
    linkVideo: '',
    src: '',
    degY: 0,
    alt: 'Site e-commerce pour la société de bijoux (projet de formation)',
    projectName: 'diamondCollection',
    openProject: true,
    openGit: true,
    openVideo: false,
  },
  {
    imageName: 'img3.webp', //dictionary
    descriptions: 'HTML|CSS|React|Bootstrap|API|GitHub',
    linkGit: 'https://github.com/TinaSemashko/dictionary_react',
    linkProject: 'https://effortless-sunburst-a3a68f.netlify.app/',
    linkVideo: '',
    src: '',
    degY: 0,
    alt: 'Application utilisant l/API Dictionnaire',
    projectName: 'dictionary',
    openProject: true,
    openGit: true,
    openVideo: false,
  },
  {
    imageName: 'img4.webp', //ekea
    descriptions: 'HTML|CSS|Javascript|Bootstrap|JSON|Local storage for Basket|GitHub',
    linkGit: 'https://github.com/Kaiju971/PROJET-NIVEAU-II',
    linkProject: 'https://magical-cocada-6863e7.netlify.app/',
    linkVideo: '',
    src: '',
    degY: 0,
    alt: 'Site e-commerce pour une entreprise de meuble (projet de formation)',
    projectName: 'ekea',
    openProject: true,
    openGit: true,
    openVideo: false,
  },
  {
    imageName: 'img5.webp', //casinoGame
    descriptions: 'HTML|CSS|Javascript|Bootstrap|GitHub',
    linkGit: 'https://github.com/TinaSemashko/AssofacCasinoGame',
    linkProject: 'https://aquamarine-gnome-52ee5d.netlify.app/',
    linkVideo: '',
    src: '',
    degY: 0,
    alt: 'Jeu de dés',
    projectName: 'casinoGame',
    openProject: true,
    openGit: true,
    openVideo: false,
  },
  {
    imageName: 'img6.webp', //garage
    descriptions: 'React|Styled-components|Typecript|Mui-material|PostgreSQL|GitHub|CRUD',
    linkGit: 'https://github.com/TinaSemashko/garage',
    linkProject: 'https://www.tina-space.fr',
    linkVideo: 'Garage',
    src: '',
    degY: 0,
    alt: 'Site e-commerce pour une entreprise de voitures (projet de formation)',
    projectName: 'Garage',
    openProject: false,
    openGit: true,
    openVideo: false,
  },

  {
    imageName: 'img8.webp', //weather_react
    descriptions: 'HTML|CSS|React|Bootstrap|API|GitHub',
    linkGit: 'https://github.com/TinaSemashko/weather_react',
    linkProject: 'https://stately-sopapillas-d6d214.netlify.app/',
    linkVideo: '',
    src: '',
    degY: 0,
    alt: 'Une application qui utilise une API pour afficher les prévisions météo d/une ville sélectionnée',
    projectName: 'weatherReact',
    openProject: true,
    openGit: true,
    openVideo: false,
  },

  {
    imageName: 'img10.webp', //connectify
    descriptions: 'React|Styled-components|Typecript|Mui-material|PostgreSQL|GitHub|CRUD',
    linkGit: 'https://github.com/TinaSemashko/connectify-plus',
    linkProject: '',
    linkVideo: 'VideoConnectify',
    src: '',
    degY: 0,
    alt: 'projet de formation',
    projectName: 'Connectify',
    openProject: false,
    openGit: true,
    openVideo: false,
  },
  {
    imageName: 'img11.webp', //assoFacTory
    descriptions: 'React|Styled-components|Javascript|Mui-material|PostgreSQL|GitHub|Work in the team|CRUD',
    linkGit: 'https://github.com/TinaSemashko/AssoFacTorySQL',
    linkProject: '',
    linkVideo: 'VideoAssofactory',
    src: '',
    degY: 0,
    alt: 'un blog (projet de formation)',
    projectName: 'AssoFacTory',
    openProject: false,
    openGit: true,
    openVideo: true,
  },
  {
    imageName: 'img9.webp', //Nastya
    descriptions: 'React|Styled-components|Typescript|Mui-material|GitHub',
    linkGit: '',
    linkProject: 'https://photo-nastya-demchuk.netlify.app/',
    linkVideo: '',
    src: '',
    degY: 0,
    alt: 'Site-vitrine pour une photographe',
    projectName: 'nastyaPhoto',
    openProject: true,
    openGit: false,
    openVideo: false,
  },
  {
    imageName: 'img7.webp', //Karamon video
    descriptions: 'React|Styled-components|Typescript|Mui-material|GitHub',
    linkGit: 'private',
    linkProject: 'https://karamon-video.netlify.app/',
    linkVideo: '',
    src: '',
    degY: 0,
    alt: 'Site-vitrine pour un ingénieur vidéo',
    projectName: 'Karamon video',
    openProject: true,
    openGit: false,
    openVideo: false,
  },
  {
    imageName: 'img12.webp', //ABS
    descriptions: 'React|Styled-components|Typecript|Mui-material|PostgreSQL|GitHub|Work in the team|CRUD',
    linkGit: 'private',
    linkProject: 'https://www.abs-couverture.fr',
    linkVideo: 'VideoABS',
    src: '',
    degY: 0,
    alt: 'Site Web e-commerse pour une entreprise de construction avec base de données, page d/administration et stockage de photos sur un service tiers',
    projectName: 'ABS',
    openProject: true,
    openGit: false,
    openVideo: true,
  },
];
